### ISSUE TITLE
تبریک

### ISSUE THREAD

**Issue by 1995parham** [mmsamiei/huggingface-workshop#1]
آقا من تبریک می‌گم و بابت عدم حضور در این رویداد پوزش می‌طلبم. خیلی خوشحال شدم که هنوز ایرانی :+1:

**Comment by mmsamiei** [comment]
سلام علیکم

شما همیشه لطف داشتین به ما

ما هم از هنوز ایران بودن شما خوشحالیم

انشالله ی روز بعد کرونا دوباره همدیگر رو از نزدیک ببینیم
